"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ListenUpApp.py']
DATA_FILES = ['icon.png']
OPTIONS = {
            'argv_emulation': True,
            'plist': {
                'LSUIElement': 1,   
            },
            'packages': ['rumps'],
          }
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
